# Lesson 3 Class Exercises: Pandas Part 1

With these class exercises we learn a few new things.  When new knowledge is introduced you'll see the icon shown on the right: 
<span style="float:right; margin-left:10px; clear:both;">![Task](../media/new_knowledge.png)</span>

## Reminder
The first checkin-in of the project is due next Tueday.  After today, you should have everything you need to know to accomplish that first part.

## Get Started
Import the Numpy and Pandas packages

In [2]:
import pandas as pd 
import numpy as np

## Exercise 1: Import Iris Data
Import the Iris dataset made available to you in the last class period for the Numpy part2 exercises. Save it to a variable naemd `iris`. Print the first 5 rows and the dimensions to ensure it was read in properly.

In [9]:
iris=pd.read_csv("data/iris.csv")
iris.shape

(150, 5)

Notice how much easier this was to import compared to the Numpy `genfromtxt`. We did not have to skip the headers, we did not have to specify the data type and we can have mixed data types in the same matrix.

## Exercise 2: Import Legislators Data
For portions of this notebook we will use a public dataset that contains all of the current legistators of the United States Congress. This dataset can be found [here](https://github.com/unitedstates/congress-legislators).  

Import the data directly from this URL:  https://theunitedstates.io/congress-legislators/legislators-current.csv

Save the data in a variable named `legistators`. Print the first 5 lines, and the dimensions. You can get the dimensions of the dataframe using the `.shape` member variable.

In [8]:
leg = pd.read_csv("/Users/ko/Downloads/legislators.csv")
leg.size
leg.shape

(540, 36)

## Exercise 3: Explore the Data
### Task 1
Print the column names of the legistators dataframe and explore the type of data in the data frame.

In [31]:
leg.columns
leg.index
leg["district"]

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
535    0.0
536    3.0
537    3.0
538    0.0
539    NaN
Name: district, Length: 540, dtype: float64

### Task 2
Show the data types of all of the columns in the legislator data. To do this, use the `.dtype` member variable. Do all of the data types seem appropriate for the data?

In [26]:
leg.dtypes

last_name              object
first_name             object
middle_name            object
suffix                 object
nickname               object
full_name              object
birthday               object
gender                 object
type                   object
state                  object
district              float64
senate_class          float64
party                  object
url                    object
address                object
phone                  object
contact_form           object
rss_url                object
twitter                object
twitter_id            float64
facebook               object
youtube                object
youtube_id             object
mastodon               object
bioguide_id            object
thomas_id             float64
opensecrets_id         object
lis_id                 object
fec_ids                object
cspan_id              float64
govtrack_id             int64
votesmart_id          float64
ballotpedia_id         object
washington_post_id    float64
icpsr_id              float64
wikipedia_id           object
dtype: object

Show all of the data types in the iris dataframe. To do this, use the `.dtype` member variable.

In [27]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

### Task 3
It's always important to know where the missing values are in your data. Are there any missing values in the legislators dataframe? How many per column?  

Hint: we didn't learn how to find missing values in the lesson, but we can use the `isna()` function.

In [39]:
leg.isna().sum()

last_name               0
first_name              0
middle_name           266
suffix                520
nickname              506
full_name               0
birthday                0
gender                  0
type                    0
state                   0
district              100
senate_class          440
party                   0
url                     4
address                 0
phone                   0
contact_form          441
rss_url               337
twitter                44
twitter_id             44
facebook              235
youtube               325
youtube_id            259
mastodon              525
bioguide_id             0
thomas_id             267
opensecrets_id         80
lis_id                440
fec_ids                 0
cspan_id              224
govtrack_id             0
votesmart_id          124
ballotpedia_id        101
washington_post_id    540
icpsr_id              156
wikipedia_id            3
dtype: int64

How about in the iris dataframe?

In [40]:
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

### Task 4
It is also important to know if you have any duplicatd rows. If you are performing statistcal analyses and you have duplicated entries they can affect the results.  So, let's find out.  Are there any duplicated rows in the legislators dataframe?  Print then number of duplicates. If there are duplicates print the rows. What function could we used to find out if we have duplicated rows?

In [42]:
leg.duplicated().sum()

AttributeError: 'function' object has no attribute 'sum'

Do we have duplicated rows in the iris dataset? Print the number of duplicates? If there are duplicates print the rows.

In [50]:
iris[iris.duplicated()]

     sepal_length  sepal_width  petal_length  petal_width    species
34            4.9          3.1           1.5          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
142           5.8          2.7           5.1          1.9  virginica

If there are duplicated rows should we remove them or keep them?

### Task 5
It is important to also check that the range of values in our data matches expectations.  For example, if we expect to have four species in our iris data, we should check that we see four species. How many political parties should we expect in the legislators data?  If all we saw were a single part perhaps the data is incomplete.... Let's check.   You can find out how many unique values there are per column using the `nunique` function.  Try it for both the legislators and the iris data set.

In [60]:
leg.nunique()
leg[leg["full_name"].duplicated()]

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
505,Menendez,Robert,Jacobsen,Jr.,NaN,Robert Menendez,1985-07-12,M,rep,NJ,...,NaN,NaN,H2NJ08232,NaN,456918,NaN,NaN,NaN,NaN,Rob Menendez

In [58]:
iris.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

What do you think?  Do we see what we might expect?  Are there fields where this type of check doesn't matter? In what fields might this type of exploration matter?

Check to see if you have all of the values expected for a given field. Pick a column you know should have a set number of values and print all of the unique values in that column. Do so for both the legislator and iris datasets.

## Exercise 5: Describe the data
For both the legislators and the iris data, get descriptive statistics for each numeric field.

In [61]:
leg.sum()

last_name             BrownCantwellCardinCarperCaseyFeinsteinKlobuch...
first_name            SherrodMariaBenjaminThomasRobertDianneAmyRober...
full_name             Sherrod BrownMaria CantwellBenjamin L. CardinT...
birthday              1952-11-091958-10-131943-10-051947-01-231960-0...
gender                MFMMMFFMMFMMMMFMMMMMMMFMFMMMFMMMFMMMMMMMFMMMFF...
type                  sensensensensensensensensensensensensensensens...
state                 OHWAMDDEPACAMNNJVTMIMTRIWYMSMETXILSCKYORRIIDNH...
district                                                         4400.0
senate_class                                                      201.0
party                 DemocratDemocratDemocratDemocratDemocratDemocr...
address               503 Hart Senate Office Building Washington DC ...
phone                 202-224-2315202-224-3441202-224-4524202-224-24...
twitter_id                                      273972024102922977280.0
bioguide_id           B000944C000127C000141C000174C001070F000062K000...
thomas_id                                                      485286.0
fec_ids               H2OH13033,S6OH00163S8WA00194,H2WA01054H6MD0317...
cspan_id                                                    170772135.0
govtrack_id                                                   226626763
votesmart_id                                                 32892183.0
washington_post_id                                                  0.0
icpsr_id                                                      9386472.0
dtype: object

In [71]:

iris.describe()
leg[leg["party"]]

KeyError: "None of [Index(['Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat',\n       'Democrat', 'Democrat', 'Independent', 'Democrat',\n       ...\n       'Republican', 'Democrat', 'Democrat', 'Republican', 'Republican',\n       'Democrat', 'Democrat', 'Republican', 'Republican', 'Republican'],\n      dtype='object', length=540)] are in the [columns]"

## Exercise 6: Row Index Labels
For the legislator dataframe, let's change the row labels from numerical indexes to something more recognizable.  Take a look at the columns of data, is there anything you might want to substitue as a row label?  Pick one and set the index lables. Then print the top 5 rows to see if the index labels are present.

In [70]:
leg.index = leg["state"]
leg.loc["PA"]

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
state,,,,,,,,,,,,,,,,,,,,,
PA,Casey,Robert,P.,Jr.,Bob,"Robert P. Casey, Jr.",1960-04-13,M,sen,PA,...,N00027503,S309,S6PA00217,47036.0,412246,2541.0,"Bob Casey, Jr.",NaN,40703.0,Bob Casey Jr.
PA,Kelly,Mike,NaN,NaN,NaN,Mike Kelly,1948-05-10,M,rep,PA,...,N00031647,NaN,H0PA03271,62696.0,412465,119463.0,Mike Kelly,NaN,21167.0,Mike Kelly (Pennsylvania politician)
PA,Thompson,Glenn,NaN,NaN,NaN,Glenn Thompson,1959-07-27,M,rep,PA,...,N00029736,NaN,H8PA05071,1031359.0,412317,24046.0,Glenn Thompson (Pennsylvania),NaN,20946.0,Glenn Thompson (politician)
PA,Perry,Scott,NaN,NaN,NaN,Scott Perry,1962-05-27,M,rep,PA,...,N00034120,NaN,H2PA04135,79873.0,412569,59980.0,Scott Perry,NaN,21356.0,Scott Perry (politician)
PA,Cartwright,Matthew,A.,NaN,Matt,Matt Cartwright,1961-05-01,M,rep,PA,...,N00034128,NaN,H2PA17079,79865.0,412571,136236.0,Matt Cartwright,NaN,21358.0,Matt Cartwright
PA,Boyle,Brendan,F.,NaN,NaN,Brendan F. Boyle,1977-02-06,M,rep,PA,...,N00035307,NaN,H4PA13199,76428.0,412652,47357.0,Brendan Boyle,NaN,21548.0,Brendan Boyle
PA,Evans,Dwight,NaN,NaN,NaN,Dwight Evans,1954-05-16,M,rep,PA,...,N00038450,NaN,H6PA02171,56729.0,412677,9128.0,Dwight Evans,NaN,21566.0,Dwight Evans (politician)
PA,Fitzpatrick,Brian,K.,NaN,NaN,Brian K. Fitzpatrick,1973-12-17,M,rep,PA,...,N00038779,NaN,H6PA08277,103537.0,412721,167708.0,Brian Fitzpatrick,NaN,21718.0,Brian Fitzpatrick (American politician)
PA,Smucker,Lloyd,NaN,NaN,NaN,Lloyd Smucker,1964-01-23,M,rep,PA,...,N00038781,NaN,H6PA16320,103540.0,412722,102454.0,Lloyd Smucker,NaN,21745.0,Lloyd Smucker
PA,Scanlon,Mary,Gay,NaN,NaN,Mary Gay Scanlon,1959-08-30,F,rep,PA,...,N00042706,NaN,H8PA07200,NaN,412750,178890.0,Mary Gay Scanlon,NaN,21762.0,Mary Gay Scanlon
PA,Wild,Susan,Ellis,NaN,NaN,Susan Wild,1957-06-07,F,rep,PA,...,N00041997,NaN,H8PA15229,NaN,412751,178895.0,Susan Wild,NaN,21763.0,Susan Wild
PA,Dean,Madeleine,NaN,NaN,NaN,Madeleine Dean,1959-06-06,F,rep,PA,...,N00042894,NaN,H8PA04116,NaN,412809,136484.0,Madeleine Dean,NaN,21915.0,Madeleine Dean
PA,Houlahan,Chrissy,NaN,NaN,NaN,Chrissy Houlahan,1967-06-05,F,rep,PA,...,N00040949,NaN,H8PA06087,NaN,412810,178893.0,Chrissy Houlahan,NaN,21934.0,Chrissy Houlahan
PA,Meuser,Daniel,NaN,NaN,NaN,Daniel Meuser,1964-02-10,M,rep,PA,...,N00029416,NaN,H8PA10147,NaN,412811,102438.0,Dan Meuser,NaN,21945.0,Dan Meuser
PA,Joyce,John,NaN,NaN,NaN,John Joyce,1957-02-08,M,rep,PA,...,N00043242,NaN,H8PA13125,NaN,412812,178911.0,John Joyce (Pennsylvania),NaN,21936.0,John Joyce (American politician)
PA,Reschenthaler,Guy,NaN,NaN,NaN,Guy Reschenthaler,1983-04-17,M,rep,PA,...,N00041871,NaN,H8PA18199,NaN,412813,166004.0,Guy Reschenthaler,NaN,21956.0,Guy Reschenthaler
PA,Fetterman,John,Karl,NaN,NaN,John Fetterman,1969-08-15,M,sen,PA,...,NaN,S418,S6PA00274,NaN,456877,166286.0,John Fetterman,NaN,NaN,John Fetterman
PA,Lee,Summer,Lynn,NaN,NaN,Summer L. Lee,1987-11-26,F,rep,PA,...,NaN,NaN,H2PA18200,NaN,456935,NaN,Summer Lee,NaN,NaN,Summer Lee
PA,Deluzio,Chris,Raphael,NaN,NaN,Christopher R. Deluzio,1984-07-13,M,rep,PA,...,NaN,NaN,H2PA17103,NaN,456936,NaN,NaN,NaN,NaN,Chris Deluzio

## Exercise 7: Indexing & Sampling
Randomly select 15 Republicans or Democrats (your choice) from the senate.

In [81]:
leg[(leg["party"]== "Democrat") & (leg["type"]== "sen")].sample(15)

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
state,,,,,,,,,,,,,,,,,,,,,
MD,Cardin,Benjamin,L.,NaN,NaN,Benjamin L. Cardin,1943-10-05,M,sen,MD,...,N00001955,S308,"H6MD03177,S6MD03177",4004.0,400064,26888.0,Ben Cardin,NaN,15408.0,Ben Cardin
DE,Coons,Christopher,Andrew,NaN,NaN,Christopher A. Coons,1963-09-09,M,sen,DE,...,N00031820,S337,S0DE00092,9269028.0,412390,122834.0,Chris Coons,NaN,40916.0,Chris Coons
RI,Reed,John,F.,NaN,Jack,Jack Reed,1949-11-12,M,sen,RI,...,N00000362,S259,"S6RI00163,H0RI02071",24239.0,300081,27060.0,Jack Reed,NaN,29142.0,Jack Reed (Rhode Island politician)
OR,Merkley,Jeff,NaN,NaN,NaN,Jeff Merkley,1956-10-24,M,sen,OR,...,N00029303,S322,S8OR00207,1029842.0,412325,23644.0,Jeff Merkley,NaN,40908.0,Jeff Merkley
MA,Warren,Elizabeth,NaN,NaN,NaN,Elizabeth Warren,1949-06-22,F,sen,MA,...,N00033492,S366,S2MA00170,1023023.0,412542,141272.0,Elizabeth Warren,NaN,41301.0,Elizabeth Warren
GA,Ossoff,Jon,NaN,NaN,NaN,Jon Ossoff,1987-02-16,M,sen,GA,...,N00040675,S414,"H8GA06195,S8GA00180",NaN,456857,176134.0,Jon Ossoff,NaN,NaN,Jon Ossoff
HI,Hirono,Mazie,K.,NaN,NaN,Mazie K. Hirono,1947-11-03,F,sen,HI,...,N00028139,S361,"H6HI02251,S2HI00106",91216.0,412200,1677.0,Mazie K. Hirono,NaN,20713.0,Mazie Hirono
CT,Murphy,Christopher,S.,NaN,NaN,Christopher Murphy,1973-08-03,M,sen,CT,...,N00027566,S364,"H6CT05124,S2CT00132",1021270.0,412194,17189.0,Christopher S. Murphy,NaN,20707.0,Chris Murphy
MI,Stabenow,Debbie,Ann,NaN,NaN,Debbie Stabenow,1950-04-29,F,sen,MI,...,N00004118,S284,"S8MI00281,H6MI08163",45451.0,300093,515.0,Debbie Stabenow,NaN,29732.0,Debbie Stabenow
IL,Durbin,Richard,J.,NaN,NaN,Richard J. Durbin,1944-11-21,M,sen,IL,...,N00004981,S253,"S6IL00151,H2IL20026",6741.0,300038,26847.0,Dick Durbin,NaN,15021.0,Dick Durbin
CT,Blumenthal,Richard,NaN,NaN,NaN,Richard Blumenthal,1946-02-13,M,sen,CT,...,N00031685,S341,S0CT00177,21799.0,412490,1568.0,Richard Blumenthal,NaN,41101.0,Richard Blumenthal
MI,Peters,Gary,C.,NaN,NaN,Gary C. Peters,1958-12-01,M,sen,MI,...,N00029277,S380,"H8MI09068,S4MI00355",50199.0,412305,8749.0,Gary Peters,NaN,20923.0,Gary Peters
NY,Gillibrand,Kirsten,E.,NaN,NaN,Kirsten E. Gillibrand,1966-12-09,F,sen,NY,...,N00027658,S331,"H6NY20167,S0NY00410",1022862.0,412223,65147.0,Kirsten Gillibrand,NaN,20735.0,Kirsten Gillibrand
DE,Carper,Thomas,Richard,NaN,NaN,Thomas R. Carper,1947-01-23,M,sen,DE,...,N00012508,S277,S8DE00079,663.0,300019,22421.0,Tom Carper,NaN,15015.0,Tom Carper
NY,Schumer,Charles,E.,NaN,Chuck,Charles E. Schumer,1950-11-23,M,sen,NY,...,N00001093,S270,"S8NY00082,H0NY16010",5929.0,300087,26976.0,Chuck Schumer,NaN,14858.0,Chuck Schumer

## Exercise 8: Dates
<span style="float:right; margin-left:10px; clear:both;">![Task](../media/new_knowledge.png)</span>
Let's learn something not covered in the Pandas 1 lesson regarding dates.  We have the birthdates for each legislator, but they are in a String format.  Let's convert it to a datetime object. We can do this using the `pd.to_datetime` function.  Take a look at the online documentation to see how to use this function. Convert the `legislators['birthday']` column to a `datetime` object. Confirm that the column is now a datetime object.

In [87]:
leg["birthday"]= pd.to_datetime(leg["birthday"])
leg.dtypes

last_name                     object
first_name                    object
middle_name                   object
suffix                        object
nickname                      object
full_name                     object
birthday              datetime64[ns]
gender                        object
type                          object
state                         object
district                     float64
senate_class                 float64
party                         object
url                           object
address                       object
phone                         object
contact_form                  object
rss_url                       object
twitter                       object
twitter_id                   float64
facebook                      object
youtube                       object
youtube_id                    object
mastodon                      object
bioguide_id                   object
thomas_id                    float64
opensecrets_id                object
lis_id                        object
fec_ids                       object
cspan_id                     float64
govtrack_id                    int64
votesmart_id                 float64
ballotpedia_id                object
washington_post_id           float64
icpsr_id                     float64
wikipedia_id                  object
dtype: object

Now that we have the birthdays in a `datetime` object, how can we calculate their age?  Hint: we can use the `pd.Timestamp.now()` function to get a datetime object for this moment. Let's subtract the current time from their birthdays.  Print the top 5 results.

In [119]:
time = pd.Timestamp.now() - leg["birthday"]
timed = time.dt.days

Notice that the result of subtracting two `datetime` objects is a `timedelta` object. It contains the difference between two time values. The value we calculated therefore gives us the number of days old.  However, we want the number of years. 

To get the number of years we can divide the number of days old by the number of days in a year (i.e. 365). However, we need to extract out the days from the `datetime` object. To get this, the Pandas Series object has an accessor for extracting components of `datetime` objects and `timedelta` objects. It's named `dt` and it works for both.  You can learn more about the attributes of this accessor at the [datetime objects page](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#datetime-properties) and the [timedelta objects page](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#timedelta-properties) by clicking.  Take a moment to look over that documentation.

How would then extract the days in order to divide by 365 to get the years?  Once you've figurd it out. Do so, convert the years to an integer and add the resulting series back into the legislator dataframe as a new column named `age`.  Hint: use the [astype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.astype.html) function of Pandas to convert the type.

In [129]:
timed.astype(int)
leg["age"]=timed/365
leg.head

<bound method NDFrame.head of                last_name first_name middle_name suffix nickname  \
state
OH                 Brown    Sherrod         NaN    NaN      NaN
WA              Cantwell      Maria         NaN    NaN      NaN
MD                Cardin   Benjamin          L.    NaN      NaN
DE                Carper     Thomas     Richard    NaN      NaN
PA                 Casey     Robert          P.    Jr.      Bob
...                  ...        ...         ...    ...      ...
VT                Balint      Becca          A.    NaN      NaN
WA     Gluesenkamp Perez      Marie         NaN    NaN      NaN
WI             Van Orden    Derrick     Francis    NaN      NaN
WY               Hageman    Harriet      Maxine    NaN      NaN
NE              Ricketts       Pete         NaN    NaN      NaN

                     full_name   birthday gender type state  ...  lis_id  \
state                                                        ...
OH               Sherrod Brown 1952-11-09      M  sen    OH  ...    S307
WA              Maria Cantwell 1958-10-13      F  sen    WA  ...    S275
MD          Benjamin L. Cardin 1943-10-05      M  sen    MD  ...    S308
DE            Thomas R. Carper 1947-01-23      M  sen    DE  ...    S277
PA        Robert P. Casey, Jr. 1960-04-13      M  sen    PA  ...    S309
...                        ...        ...    ...  ...   ...  ...     ...
VT                Becca Balint 1968-05-04      F  rep    VT  ...     NaN
WA     Marie Gluesenkamp Perez 1988-06-06      F  rep    WA  ...     NaN
WI           Derrick Van Orden 1969-09-15      M  rep    WI  ...     NaN
WY          Harriet M. Hageman 1962-10-18      F  rep    WY  ...     NaN
NE               Pete Ricketts 1964-08-19      M  sen    NE  ...    S423

                   fec_ids cspan_id govtrack_id votesmart_id  \
state
OH     H2OH13033,S6OH00163   5051.0      400050      27018.0
WA     S8WA00194,H2WA01054  26137.0      300018      27122.0
MD     H6MD03177,S6MD03177   4004.0      400064      26888.0
DE               S8DE00079    663.0      300019      22421.0
PA               S6PA00217  47036.0      412246       2541.0
...                    ...      ...         ...          ...
VT               H2VT01076      NaN      456948          NaN
WA               H2WA03217      NaN      456949          NaN
WI               H0WI03175      NaN      456950          NaN
WY               H2WY00166      NaN      456951          NaN
NE               S6NE00129  61233.0      456952      57777.0

                ballotpedia_id washington_post_id icpsr_id  \
state
OH               Sherrod Brown                NaN  29389.0
WA              Maria Cantwell                NaN  39310.0
MD                  Ben Cardin                NaN  15408.0
DE                  Tom Carper                NaN  15015.0
PA              Bob Casey, Jr.                NaN  40703.0
...                        ...                ...      ...
VT                         NaN                NaN      NaN
WA     Marie Gluesenkamp Perez                NaN      NaN
WI           Derrick Van Orden                NaN      NaN
WY             Harriet Hageman                NaN      NaN
NE               Pete Ricketts                NaN      NaN

                  wikipedia_id        age
state
OH               Sherrod Brown  70.336986
WA              Maria Cantwell  64.408219
MD                  Ben Cardin  79.441096
DE                  Tom Carper  76.136986
PA               Bob Casey Jr.  62.906849
...                        ...        ...
VT                Becca Balint  54.843836
WA     Marie Gluesenkamp Perez  34.739726
WI           Derrick Van Orden  53.476712
WY             Harriet Hageman  60.391781
NE               Pete Ricketts  58.553425

[540 rows x 37 columns]>

Next, find the youngest, oldest and average age of all legislators

In [ ]:
timed

Who are the oldest and youngest legislators?

In [128]:
leg[leg["age"] == leg["age"].max()]

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id,age
state,,,,,,,,,,,,,,,,,,,,,
CA,Feinstein,Dianne,NaN,NaN,NaN,Dianne Feinstein,1933-06-22,F,sen,CA,...,S221,S0CA00199,13061.0,300043,53273.0,Dianne Feinstein,NaN,49300.0,Dianne Feinstein,89.734247

## Exercise 9:  Indexing with loc and iloc
Reindex the legislators dataframe using the state, and find all legislators from a state of your choice using the `loc` accessor.

In [143]:
leg[leg.index == "PA"]
leg.loc["PA"]

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id,age
state,,,,,,,,,,,,,,,,,,,,,
PA,Casey,Robert,P.,Jr.,Bob,"Robert P. Casey, Jr.",1960-04-13,M,sen,PA,...,S309,S6PA00217,47036.0,412246,2541.0,"Bob Casey, Jr.",NaN,40703.0,Bob Casey Jr.,62.906849
PA,Kelly,Mike,NaN,NaN,NaN,Mike Kelly,1948-05-10,M,rep,PA,...,NaN,H0PA03271,62696.0,412465,119463.0,Mike Kelly,NaN,21167.0,Mike Kelly (Pennsylvania politician),74.841096
PA,Thompson,Glenn,NaN,NaN,NaN,Glenn Thompson,1959-07-27,M,rep,PA,...,NaN,H8PA05071,1031359.0,412317,24046.0,Glenn Thompson (Pennsylvania),NaN,20946.0,Glenn Thompson (politician),63.621918
PA,Perry,Scott,NaN,NaN,NaN,Scott Perry,1962-05-27,M,rep,PA,...,NaN,H2PA04135,79873.0,412569,59980.0,Scott Perry,NaN,21356.0,Scott Perry (politician),60.786301
PA,Cartwright,Matthew,A.,NaN,Matt,Matt Cartwright,1961-05-01,M,rep,PA,...,NaN,H2PA17079,79865.0,412571,136236.0,Matt Cartwright,NaN,21358.0,Matt Cartwright,61.857534
PA,Boyle,Brendan,F.,NaN,NaN,Brendan F. Boyle,1977-02-06,M,rep,PA,...,NaN,H4PA13199,76428.0,412652,47357.0,Brendan Boyle,NaN,21548.0,Brendan Boyle,46.076712
PA,Evans,Dwight,NaN,NaN,NaN,Dwight Evans,1954-05-16,M,rep,PA,...,NaN,H6PA02171,56729.0,412677,9128.0,Dwight Evans,NaN,21566.0,Dwight Evans (politician),68.821918
PA,Fitzpatrick,Brian,K.,NaN,NaN,Brian K. Fitzpatrick,1973-12-17,M,rep,PA,...,NaN,H6PA08277,103537.0,412721,167708.0,Brian Fitzpatrick,NaN,21718.0,Brian Fitzpatrick (American politician),49.219178
PA,Smucker,Lloyd,NaN,NaN,NaN,Lloyd Smucker,1964-01-23,M,rep,PA,...,NaN,H6PA16320,103540.0,412722,102454.0,Lloyd Smucker,NaN,21745.0,Lloyd Smucker,59.126027
PA,Scanlon,Mary,Gay,NaN,NaN,Mary Gay Scanlon,1959-08-30,F,rep,PA,...,NaN,H8PA07200,NaN,412750,178890.0,Mary Gay Scanlon,NaN,21762.0,Mary Gay Scanlon,63.528767
PA,Wild,Susan,Ellis,NaN,NaN,Susan Wild,1957-06-07,F,rep,PA,...,NaN,H8PA15229,NaN,412751,178895.0,Susan Wild,NaN,21763.0,Susan Wild,65.758904
PA,Dean,Madeleine,NaN,NaN,NaN,Madeleine Dean,1959-06-06,F,rep,PA,...,NaN,H8PA04116,NaN,412809,136484.0,Madeleine Dean,NaN,21915.0,Madeleine Dean,63.761644
PA,Houlahan,Chrissy,NaN,NaN,NaN,Chrissy Houlahan,1967-06-05,F,rep,PA,...,NaN,H8PA06087,NaN,412810,178893.0,Chrissy Houlahan,NaN,21934.0,Chrissy Houlahan,55.758904
PA,Meuser,Daniel,NaN,NaN,NaN,Daniel Meuser,1964-02-10,M,rep,PA,...,NaN,H8PA10147,NaN,412811,102438.0,Dan Meuser,NaN,21945.0,Dan Meuser,59.076712
PA,Joyce,John,NaN,NaN,NaN,John Joyce,1957-02-08,M,rep,PA,...,NaN,H8PA13125,NaN,412812,178911.0,John Joyce (Pennsylvania),NaN,21936.0,John Joyce (American politician),66.084932
PA,Reschenthaler,Guy,NaN,NaN,NaN,Guy Reschenthaler,1983-04-17,M,rep,PA,...,NaN,H8PA18199,NaN,412813,166004.0,Guy Reschenthaler,NaN,21956.0,Guy Reschenthaler,39.882192
PA,Fetterman,John,Karl,NaN,NaN,John Fetterman,1969-08-15,M,sen,PA,...,S418,S6PA00274,NaN,456877,166286.0,John Fetterman,NaN,NaN,John Fetterman,53.561644
PA,Lee,Summer,Lynn,NaN,NaN,Summer L. Lee,1987-11-26,F,rep,PA,...,NaN,H2PA18200,NaN,456935,NaN,Summer Lee,NaN,NaN,Summer Lee,35.268493
PA,Deluzio,Chris,Raphael,NaN,NaN,Christopher R. Deluzio,1984-07-13,M,rep,PA,...,NaN,H2PA17103,NaN,456936,NaN,NaN,NaN,NaN,Chris Deluzio,38.641096

Use the loc command to find all legislators from South Carolina and North Carolina

In [146]:
leg.loc[["SC","NC"]]

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id,age
state,,,,,,,,,,,,,,,,,,,,,
SC,Graham,Lindsey,O.,NaN,NaN,Lindsey Graham,1955-07-09,M,sen,SC,...,S293,"S0SC00149,H4SC03087",36782.0,300047,21992.0,Lindsey Graham,NaN,29566.0,Lindsey Graham,67.673973
SC,Clyburn,James,E.,NaN,Jim,James E. Clyburn,1940-07-21,M,rep,SC,...,NaN,H2SC02042,21607.0,400075,27066.0,James E. Clyburn,NaN,39301.0,Jim Clyburn,82.649315
SC,Duncan,Jeff,NaN,NaN,NaN,Jeff Duncan,1966-01-07,M,rep,SC,...,NaN,H0SC03077,62713.0,412472,47967.0,Jeff Duncan,NaN,21174.0,Jeff Duncan (politician),57.167123
SC,Scott,Tim,NaN,NaN,NaN,Tim Scott,1965-09-19,M,sen,SC,...,S365,"H0SC01279,S4SC00240",623506.0,412471,11940.0,Tim Scott,NaN,21173.0,Tim Scott,57.468493
SC,Wilson,Joe,G.,NaN,NaN,Joe Wilson,1947-07-31,M,rep,SC,...,NaN,H2SC02059,1002567.0,400433,3985.0,Joe Wilson,NaN,20138.0,Joe Wilson (American politician),75.619178
SC,Norman,Ralph,NaN,NaN,NaN,Ralph Norman,1953-06-20,M,rep,SC,...,NaN,H8SC05158,61996.0,412738,47930.0,Ralph Norman,NaN,21753.0,Ralph Norman,69.726027
SC,Timmons,William,R.,NaN,NaN,William R. Timmons IV,1984-04-30,M,rep,SC,...,NaN,H8SC04250,NaN,412815,168923.0,William Timmons,NaN,21974.0,William Timmons,38.843836
SC,Mace,Nancy,Ruth,NaN,NaN,Nancy Mace,1977-12-04,F,rep,SC,...,NaN,H0SC01394,NaN,456843,NaN,Nancy Mace,NaN,NaN,Nancy Mace,45.252055
SC,Fry,Russell,William,NaN,NaN,Russell Fry,1985-01-31,M,rep,SC,...,NaN,H2SC07280,NaN,456938,NaN,NaN,NaN,NaN,Russell Fry (politician),38.087671
NC,Foxx,Virginia,NaN,NaN,NaN,Virginia Foxx,1943-06-29,F,rep,NC,...,NaN,H4NC05146,1013052.0,400643,6051.0,Virginia Foxx,NaN,20521.0,Virginia Foxx,79.709589
NC,McHenry,Patrick,T.,NaN,NaN,Patrick T. McHenry,1975-10-22,M,rep,NC,...,NaN,H4NC10047,1007062.0,400644,21031.0,Patrick T. McHenry,NaN,20522.0,Patrick McHenry,47.372603
NC,Hudson,Richard,NaN,NaN,NaN,Richard Hudson,1971-11-04,M,rep,NC,...,NaN,H2NC08185,79622.0,412550,136448.0,Richard Hudson,NaN,21346.0,Richard Hudson (American politician),51.339726
NC,Adams,Alma,S.,NaN,NaN,Alma S. Adams,1946-05-27,F,rep,NC,...,NaN,H4NC12100,76386.0,412607,5935.0,Alma Adams,NaN,21545.0,Alma Adams,76.797260
NC,Rouzer,David,NaN,NaN,NaN,David Rouzer,1972-02-16,M,rep,NC,...,NaN,H2NC07096,79710.0,412641,102964.0,David Rouzer,NaN,21544.0,David Rouzer,51.054795
NC,Tillis,Thom,NaN,NaN,NaN,Thom Tillis,1960-08-30,M,sen,NC,...,S384,S4NC00162,77055.0,412668,57717.0,Thom Tillis (North Carolina),NaN,41504.0,Thom Tillis,62.526027
NC,Budd,Ted,NaN,NaN,NaN,Ted Budd,1971-10-21,M,sen,NC,...,S417,H6NC13129,103513.0,412712,171489.0,Ted Budd,NaN,21708.0,Ted Budd,51.378082
NC,Bishop,Dan,NaN,NaN,NaN,Dan Bishop,1964-07-01,M,rep,NC,...,NaN,H0NC09187,NaN,412844,92423.0,Dan Bishop,NaN,21986.0,Dan Bishop,58.687671
NC,Murphy,Gregory,Francis,NaN,NaN,Gregory F. Murphy,1963-03-05,M,rep,NC,...,NaN,H0NC03172,NaN,412845,166135.0,Gregory Murphy,NaN,21987.0,Greg Murphy (politician),60.013699
NC,Ross,Deborah,Koff,NaN,NaN,Deborah K. Ross,1963-06-20,F,rep,NC,...,NaN,H0NC02125,NaN,456831,NaN,Deborah Ross,NaN,NaN,Deborah K. Ross,59.720548
NC,Manning,Kathy,Ellen,NaN,NaN,Kathy E. Manning,1956-12-03,F,rep,NC,...,NaN,H8NC13067,NaN,456832,NaN,NaN,NaN,NaN,Kathy Manning,66.268493
NC,Davis,Donald,Gene,NaN,NaN,Donald G. Davis,1971-08-29,M,rep,NC,...,NaN,H2NC02287,NaN,456912,NaN,NaN,NaN,NaN,Donald G. Davis,51.523288
NC,Foushee,Valerie,Jean,NaN,NaN,Valerie P. Foushee,1956-05-07,F,rep,NC,...,NaN,H2NC06114,NaN,456913,NaN,NaN,NaN,NaN,Valerie Foushee,66.843836
NC,Edwards,Charles (Chuck),Marion,NaN,NaN,Chuck Edwards,1960-09-13,M,rep,NC,...,NaN,H2NC14050,NaN,456914,NaN,NaN,NaN,NaN,Chuck Edwards,62.487671
NC,Nickel,George,Wiley (uses as 1st),III,NaN,Wiley Nickel,1975-11-23,M,rep,NC,...,NaN,H2NC14019,NaN,456915,NaN,NaN,NaN,NaN,Wiley Nickel,47.284932
NC,Jackson,Jeffrey,Neale,NaN,NaN,Jeff Jackson,1982-09-12,M,rep,NC,...,NaN,H2NC14076,NaN,456916,NaN,NaN,NaN,NaN,Jeff Jackson (politician),40.476712

Use the loc command to retrieve all legislators from California, Oregon and Washington and only get their full name, state, party and age

In [156]:
leg.loc[["CA","OR", "WA"]][["first_name", "state", "party", "age"
                           ]]

      first_name state       party        age
state
CA        Dianne    CA    Democrat  89.734247
CA           Ken    CA  Republican  69.758904
CA          Judy    CA    Democrat  69.679452
CA           Jim    CA    Democrat  70.912329
CA          Anna    CA    Democrat  80.252055
...          ...   ...         ...        ...
WA           Dan    WA  Republican  67.671233
WA       Pramila    WA    Democrat  57.463014
WA           Kim    WA    Democrat  54.539726
WA       Marilyn    WA    Democrat  60.454795
WA         Marie    WA    Democrat  34.739726

[74 rows x 4 columns]

## Exercise 10: Economics Data Example
### Task 1: Explore the data
Import the data from the [Lectures in Quantiatives Economics](https://github.com/QuantEcon/lecture-source-py) regarding minimum wages in countries round the world in US Dollars.  You can view the data [here](https://github.com/QuantEcon/lecture-source-py/blob/master/source/_static/lecture_specific/pandas_panel/realwage.csv) and you can access the data file here: https://raw.githubusercontent.com/QuantEcon/lecture-source-py/master/source/_static/lecture_specific/pandas_panel/realwage.csv.  Then perform the following

Import and print the first 5 lines of data to explore what is there.

Find the shape of the data.

List the column names.

Identify the data types. Do they match what you would expect?

Identify columns with missing values.

Identify if there are duplicated entires.

How many unique values per row are there.  Do these look reasonable for the data type and what you know about what is stored in the column?

### Task 2: Explore More
Retrieve descriptive statistics for the data.

Identify all of the countries listed in the data.

Convert the time column to a datetime object.

Identify the time points that were used for data collection. How many years of data collection were there? What time of year were the data collected?

Because we only have one data point collected per year per country, simplify this by creating a new `Series` with just the year.  Print the first 5 rows to confirm the column was added.

There are two pay periods.  Retrieve them in a list of just the two strings

### Task 3: Clean the data
We have no duplicates in this data so we do not need to consider removing those, but we do have missing values in the `value` column. Lets remove those.  Check the dimensions afterwards to make sure they rows with missing values are gone.

### Task 4:  Indexing
Use boolean indexing to retrieve the rows of annual salary in United States

Do we have enough data to calculate descriptive statistics for annual salary in the United States in 2016?

Use loc to calculate descriptive statistics for the hourly salary in the United States and then again separately for Ireland. Hint: you will have to set row indexes.

Now do the same for Annual salary